<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.kultur' => '02483b34374ac6705a3d45675d51e14174583712',
  'content_type.panel' => '141f9a4c5f83821fa6725201e5a3a2496daaa796',
  'page_manager_pages.frontpage' => '1a48830338797304da7075ebe86337f0da1bf8c9',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'panels_node_hook',
  'ctools',
  'page_manager',
);
